# Where to store the output
output_dir:                  "./emulators_tuning_8/"

# The training, validation and test data (in .csv format)
trainingdata_csvfile_path:   "./generate_data/50_separatedLHS_train.csv"
validationdata_csvfile_path: "./generate_data/50_separatedLHS_val.csv"
testdata_csvfile_path:       "./generate_data/50_separatedLHS_test.csv"

# Define the data in the train/test/val data-sets
# 1. The columns of the parameters (the first columns in the data)
feature_columns:             ['mu0','Omegacdm','h','As','z','log10k']

# 2. The results (what we are trying to emulate - the last columns in the data)
label_columns:               ['boost']

# Architechture and training parameters
batch_size:                  32 
nthreads:                    32                   
hidden_layers:               [128,64,32]
learning_rate:               3.e-4
weight_decay:                5.e-7
activation_function:         'gelu'
loss_function:               'L1Loss'
max_epochs:                  500
